//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfEntity.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Persona", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary1")]
    [System.SerializableAttribute()]
    public partial class Persona : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char DvRutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EdadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RutField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char DvRut {
            get {
                return this.DvRutField;
            }
            set {
                if ((this.DvRutField.Equals(value) != true)) {
                    this.DvRutField = value;
                    this.RaisePropertyChanged("DvRut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Edad {
            get {
                return this.EdadField;
            }
            set {
                if ((this.EdadField.Equals(value) != true)) {
                    this.EdadField = value;
                    this.RaisePropertyChanged("Edad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Rut {
            get {
                return this.RutField;
            }
            set {
                if ((this.RutField.Equals(value) != true)) {
                    this.RutField = value;
                    this.RaisePropertyChanged("Rut");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertarPersona", ReplyAction="http://tempuri.org/IService1/InsertarPersonaResponse")]
        bool InsertarPersona(WcfEntity.ServiceReference1.Persona p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertarPersona", ReplyAction="http://tempuri.org/IService1/InsertarPersonaResponse")]
        System.Threading.Tasks.Task<bool> InsertarPersonaAsync(WcfEntity.ServiceReference1.Persona p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SeleccionarPersonaPorId", ReplyAction="http://tempuri.org/IService1/SeleccionarPersonaPorIdResponse")]
        WcfEntity.ServiceReference1.Persona SeleccionarPersonaPorId(WcfEntity.ServiceReference1.Persona p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SeleccionarPersonaPorId", ReplyAction="http://tempuri.org/IService1/SeleccionarPersonaPorIdResponse")]
        System.Threading.Tasks.Task<WcfEntity.ServiceReference1.Persona> SeleccionarPersonaPorIdAsync(WcfEntity.ServiceReference1.Persona p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarPersona", ReplyAction="http://tempuri.org/IService1/ActualizarPersonaResponse")]
        bool ActualizarPersona(WcfEntity.ServiceReference1.Persona p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarPersona", ReplyAction="http://tempuri.org/IService1/ActualizarPersonaResponse")]
        System.Threading.Tasks.Task<bool> ActualizarPersonaAsync(WcfEntity.ServiceReference1.Persona p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EliminarPersona", ReplyAction="http://tempuri.org/IService1/EliminarPersonaResponse")]
        bool EliminarPersona(WcfEntity.ServiceReference1.Persona p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EliminarPersona", ReplyAction="http://tempuri.org/IService1/EliminarPersonaResponse")]
        System.Threading.Tasks.Task<bool> EliminarPersonaAsync(WcfEntity.ServiceReference1.Persona p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SeleccionarPersonas", ReplyAction="http://tempuri.org/IService1/SeleccionarPersonasResponse")]
        WcfEntity.ServiceReference1.Persona[] SeleccionarPersonas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SeleccionarPersonas", ReplyAction="http://tempuri.org/IService1/SeleccionarPersonasResponse")]
        System.Threading.Tasks.Task<WcfEntity.ServiceReference1.Persona[]> SeleccionarPersonasAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WcfEntity.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WcfEntity.ServiceReference1.IService1>, WcfEntity.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool InsertarPersona(WcfEntity.ServiceReference1.Persona p) {
            return base.Channel.InsertarPersona(p);
        }
        
        public System.Threading.Tasks.Task<bool> InsertarPersonaAsync(WcfEntity.ServiceReference1.Persona p) {
            return base.Channel.InsertarPersonaAsync(p);
        }
        
        public WcfEntity.ServiceReference1.Persona SeleccionarPersonaPorId(WcfEntity.ServiceReference1.Persona p) {
            return base.Channel.SeleccionarPersonaPorId(p);
        }
        
        public System.Threading.Tasks.Task<WcfEntity.ServiceReference1.Persona> SeleccionarPersonaPorIdAsync(WcfEntity.ServiceReference1.Persona p) {
            return base.Channel.SeleccionarPersonaPorIdAsync(p);
        }
        
        public bool ActualizarPersona(WcfEntity.ServiceReference1.Persona p) {
            return base.Channel.ActualizarPersona(p);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarPersonaAsync(WcfEntity.ServiceReference1.Persona p) {
            return base.Channel.ActualizarPersonaAsync(p);
        }
        
        public bool EliminarPersona(WcfEntity.ServiceReference1.Persona p) {
            return base.Channel.EliminarPersona(p);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarPersonaAsync(WcfEntity.ServiceReference1.Persona p) {
            return base.Channel.EliminarPersonaAsync(p);
        }
        
        public WcfEntity.ServiceReference1.Persona[] SeleccionarPersonas() {
            return base.Channel.SeleccionarPersonas();
        }
        
        public System.Threading.Tasks.Task<WcfEntity.ServiceReference1.Persona[]> SeleccionarPersonasAsync() {
            return base.Channel.SeleccionarPersonasAsync();
        }
    }
}
